# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hu0ZJFK5wtr3-FzJduOGK5l3uLqOd0z4
"""

# calculate_sum.py
def calculate_sum(numbers):
    return sum(numbers)

if __name__ == "__main__":
    example = [1, 2, 3, 4, 5]
    total = calculate_sum(example)
    print(f"The sum is: {total}")