# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoboxarAqurW2puPgXYDqMe9WXF1ZrPa
"""

# hello_world.py
def say_hello():
    print("Hello, world!")

if __name__ == "__main__":
    say_hello()